import type { NextPage } from "next";
import Head from "next/head";
import Card from "@components/Card";
import TopNavbar from "@components/TopNavbar";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Trust the process</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <TopNavbar />
      <main className="container mx-auto flex flex-col items-center justify-center min-h-screen p-4">
        <h1 className="text-5xl md:text-[5rem] leading-normal font-extrabold text-gray-700">
          Pick your <span className="text-purple-300">Poison</span>
        </h1>
        <div className="grid gap-3 pt-3 mt-3 text-center md:grid-cols-2">
          <Card
            name="Planning Poker"
            description="Number-coded playing cards are used to estimate an item"
            documentation="https://www.atlassian.com/blog/platform/a-brief-overview-of-planning-poker"
          />
          <Card
            name="Bucket System"
            description="User stories (items) are placed within buckets (columns)"
            documentation="https://www.techagilist.com/agile/scrum/bucket-system-agile-estimation-method/"
            unavailable
          />
          <Card
            name="Three-Point Method"
            description="User stories (items) are estimated using a three-point method"
            documentation="https://tailwindcss.com/"
            unavailable
          />
        </div>
      </main>
    </>
  );
};

export default Home;
