import TopNavbar from "@components/TopNavbar";
import Head from "next/head";

const Layout = ({ children }) => {
  return (
    <>
      <Head>
        <title>Trust the process</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <TopNavbar />
      <main className="container mx-auto flex flex-col items-center justify-center min-h-screen p-4">
        {children}
      </main>
    </>
  );
};

export default Layout;
