import TopNavbar from "@components/TopNavbar";
import Head from "next/head";

const Layout = ({ children }: { children: JSX.Element }) => {
  return (
    <>
      <Head>
        <title>Trust the process</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
        <script
          async
          src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-2773408400548243"
          crossOrigin="anonymous"
        ></script>
      </Head>

      <TopNavbar />
      <main className="container mx-auto flex flex-col items-center justify-center min-h-screen p-4">
        {children}
      </main>
    </>
  );
};

export default Layout;
